name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wadmp/newdocs.wadmp.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm ci && npm run docs:build
        BUILD_DIR: src/.vuepress/dist
        CNAME: https://newdocs.wadmp.com